version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    image: pranav1306/mern-projects:chat-app-frontend
    ports:
      - "80:80"
    networks:
      - chat-app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: pranav1306/mern-projects:chat-app-backend
    ports:
      - "5000:5000"
    networks:
      - chat-app-network
    environment:
      - MONGO_URI=${MONGO_URI}
      - SESSION_SECRET=${SESSION_SECRET}

networks:
  chat-app-network:
